export enum SocketEnum {
  UPDATE_PROFILE = "UPDATE_PROFILE",
  START_GAME = "START_GAME",
  END_GAME = "END_GAME",
  UPDATE_MEMBERS = "UPDATE_MEMBERS",

  REFRESH_PLAYERS = "REFRESH_PLAYERS",
  SET_ROOM_HOST = "SET_ROOM_HOST",

  SPIN = "SPIN",
  PLAYER_SELECTED = "PLAYER_SELECTED",
}

export const config = {
  SPIN_TIME: 5000,
  PLAYER_SELECTED_TIME: 7000,
};
