export enum SocketEnum {
  UPDATE_PROFILE = "UPDATE_PROFILE",
  START_GAME = "START_GAME",
  END_GAME = "END_GAME",
  PLAY_AGAIN = 'PLAY_AGAIN',

  UPDATE_MEMBERS = "UPDATE_MEMBERS",

  REFRESH_PLAYERS = "REFRESH_PLAYERS",
  SET_ROOM_HOST = "SET_ROOM_HOST",

  SPIN = "SPIN",
  PLAYER_SELECTED = "PLAYER_SELECTED",

  PICK_PROMPT = "PICK_PROMPT",
  TRUTH_PROMPT_SELECTED = "TRUTH_PROMPT_SELECTED",
  TRICK_PROMPT_SELECTED = "TRICK_PROMPT_SELECTED",
  END_TURN = "END_TURN",
}

export const config = {
  SPIN_TIME: 7000,
  PLAYER_SELECTED_TIME: 7000,

  TIME_CLOSE_POPUP_SELECTED_PLAYER: 4000,

  // Prompt selection timing
  PROMPT_SELECTION_TIME: 10000, // 10 seconds for prompt selection
};
